export const PARTY_MOMENT_PHOTO_CHALLENGE = [
  'Take a group photo with the same emotion',
  'A photo of a moment of silence',
  'A photo without smiles',
  'Take a photo where everyone is looking in different directions',
  'A photo with an “ok” gesture',
  'Take a photo of the table after the game',
  'A photo with the most serious faces',
  'A photo with minimal light',
  'A photo where everyone is sitting calmly',
  'Take a photo without moving',
  'A photo of a moment of pause',
  'A photo without posing',
  'Take a photo with the same gesture on everyone',
  'A photo with a neutral facial expression',
  'A photo where everyone is looking at the camera silently',
  'A photo of the company at one moment',
  'Take a photo without changing the pose',
  'A photo with the simplest possible background',
  'A photo without emotions',
  'A photo “as is”, without preparation',
];
